PATH_DATASET = './data.csv'

PATH_MODELS = './models/'

# Column names for the archery dataset
COLUMN_ARCHER_ID = 'ArcherID'
COLUMN_DATE = 'Date'
COLUMN_SCORE = 'Score'
COLUMN_ROUND = 'Round'
COLUMN_ROUND_NAME = 'RoundName'
COLUMN_MAX_SCORE = 'MaxScore'

MODEL_TYPE_LSTM = 'lstm'
MODEL_TYPE_GRU = 'gru'
MODEL_TYPE_TFMR = 'tfmr'
MODEL_TYPES = [MODEL_TYPE_LSTM, MODEL_TYPE_GRU, MODEL_TYPE_TFMR]
MODEL_DISPLAY_NAMES = {MODEL_TYPE_LSTM: 'LSTM', MODEL_TYPE_GRU: 'GRU', MODEL_TYPE_TFMR: 'Transformer'}
